import {
  Activity,
  ArrowLeft,
  BadgeCheck,
  Ban,
  Bell,
  BellOff,
  Bike,
  BookOpen,
  Building,
  Calendar,
  Car,
  CarFront,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  ClipboardList,
  Clock,
  Copy,
  Cross,
  Crosshair,
  Database,
  Dot,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File as FileIcon,
  Filter,
  Flag,
  Flame,
  Footprints,
  Gauge,
  Hash,
  HeartHandshake,
  Image as ImageIcon,
  Inbox,
  Info,
  Landmark,
  LayoutDashboard,
  List,
  LoaderCircle,
  LocateFixed,
  Lock,
  LogIn,
  LogOut,
  type LucideProps,
  Mail,
  Map as MapIcon,
  MapPin,
  MapPinned,
  Megaphone,
  Menu,
  Minus,
  Monitor,
  Moon,
  MoreVertical,
  Music,
  Navigation,
  OctagonAlert,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  Route,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Sun,
  Swords,
  Tent,
  TimerOff,
  Tornado,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Upload,
  User,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Video,
  Waves,
  WifiOff,
  X,
} from 'lucide-react';
import type { ComponentType } from 'react';

/**
 * Maps the kebab-case icon names used across the shared presentation config and
 * the database (category / guide `icon` columns) to concrete lucide components.
 * Curated rather than importing all of lucide so the bundle stays small — this
 * matters for the low-bandwidth / data-saver requirement. Unknown names fall
 * back to a neutral marker so the UI always renders something meaningful.
 */
const ICONS: Record<string, ComponentType<LucideProps>> = {
  // Risk / severity / verification
  'octagon-alert': OctagonAlert,
  'triangle-alert': TriangleAlert,
  'alert-circle': CircleAlert,
  'shield-check': ShieldCheck,
  'circle-help': CircleHelp,
  info: Info,
  'badge-check': BadgeCheck,
  search: Search,
  clock: Clock,
  'x-circle': CircleX,
  'timer-off': TimerOff,
  // Safe-location types
  tent: Tent,
  cross: Cross,
  shield: Shield,
  flame: Flame,
  building: Building,
  'heart-handshake': HeartHandshake,
  'map-pin': MapPin,
  // Crisis categories (seeded)
  waves: Waves,
  'car-front': CarFront,
  megaphone: Megaphone,
  users: Users,
  landmark: Landmark,
  'user-x': UserX,
  swords: Swords,
  'shield-alert': ShieldAlert,
  tornado: Tornado,
  // UI / navigation
  menu: Menu,
  x: X,
  bell: Bell,
  'bell-off': BellOff,
  user: User,
  'log-out': LogOut,
  'log-in': LogIn,
  'user-plus': UserPlus,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  map: MapIcon,
  'map-pinned': MapPinned,
  list: List,
  plus: Plus,
  minus: Minus,
  upload: Upload,
  download: Download,
  trash: Trash2,
  check: Check,
  'check-check': CheckCheck,
  'circle-check': CircleCheck,
  'external-link': ExternalLink,
  loader: LoaderCircle,
  navigation: Navigation,
  route: Route,
  'book-open': BookOpen,
  'layout-dashboard': LayoutDashboard,
  gauge: Gauge,
  hash: Hash,
  filter: Filter,
  refresh: RefreshCw,
  locate: LocateFixed,
  crosshair: Crosshair,
  phone: Phone,
  mail: Mail,
  lock: Lock,
  calendar: Calendar,
  'arrow-left': ArrowLeft,
  eye: Eye,
  'eye-off': EyeOff,
  copy: Copy,
  inbox: Inbox,
  flag: Flag,
  'wifi-off': WifiOff,
  image: ImageIcon,
  file: FileIcon,
  video: Video,
  music: Music,
  send: Send,
  ban: Ban,
  car: Car,
  bike: Bike,
  footprints: Footprints,
  'shield-x': ShieldX,
  'user-check': UserCheck,
  'clipboard-list': ClipboardList,
  database: Database,
  activity: Activity,
  'trending-up': TrendingUp,
  pencil: Pencil,
  save: Save,
  'more-vertical': MoreVertical,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  dot: Dot,
  circle: Circle,
};

export interface IconProps extends LucideProps {
  name: string;
}

/**
 * Renders a lucide icon by its kebab-case name. Decorative by default
 * (`aria-hidden`); pass `aria-label` and `role="img"` to make it meaningful to
 * assistive technology.
 */
export function Icon({ name, 'aria-label': ariaLabel, ...props }: IconProps) {
  const Component = ICONS[name] ?? Circle;
  return <Component aria-hidden={ariaLabel ? undefined : true} aria-label={ariaLabel} {...props} />;
}

export function hasIcon(name: string): boolean {
  return name in ICONS;
}
